In [47]:
import sys
import os
import scipy
import sklearn
import pandas as pd
import numpy as np
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [112]:
f = open("house-votes-84.data.txt","r")

rows=[]
lines = f.readlines()
for line in lines:
    arow = line.strip("\n").split(",")
    for j in range(len(arow)):
        if arow[j] is 'y':
            arow[j] = "1"
        elif arow[j] is 'n':
            arow[j] = "-1"
        elif arow[j] is '?':
            arow[j] = "0"
    rows.append(arow)

    
# After you run this go delete the first line of the file then run getFolds.sh
main_df = pd.DataFrame(rows)
main_df.to_csv("CLEANED-house-votes-84.data.txt", sep=",")

main_df.head()

0   1  2   3   4  5  6   7   8   9   10  11  12 13  14  15  16
0  republican  -1  1  -1   1  1  1  -1  -1  -1   1   0   1  1   1  -1   1
1  republican  -1  1  -1   1  1  1  -1  -1  -1  -1  -1   1  1   1  -1   0
2    democrat   0  1   1   0  1  1  -1  -1  -1  -1   1  -1  1   1  -1  -1
3    democrat  -1  1   1  -1  0  1  -1  -1  -1  -1   1  -1  1  -1  -1   1
4    democrat   1  1   1  -1  1  1  -1  -1  -1  -1   1   0  1   1   1   1

In [129]:
# Get accuracy of the first fold

df_test1 = pd.read_csv("test1.txt", sep=",", names=[str(i) for i in range(18)])
df_train1 = pd.read_csv("train1.txt", sep=",", names=[str(i) for i in range(18)])


X = df_train1.ix[:,2:].as_matrix()
y = df_train1.ix[:,1].as_matrix()

x0 = df_test1.ix[:,2:].as_matrix()
y_true = df_test1.ix[:,1].as_matrix()

clf = SVC(C=1.0,kernel='linear')
"""
This code snippet lets you use the Gaussian kernel with a specified gamma and C
SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)
    
This code snippet allows for a linear kernel
SVC(C=1.0,kernel='linear')
"""
clf.fit(X, y) 

y_pred = clf.predict(x0)



print confusion_matrix(y_true, y_pred)
print accuracy_score(y_true, y_pred)
acc1 = accuracy_score(y_true, y_pred)

[[68  1]
 [ 2 38]]
0.97247706422


In [131]:
# Get the accuracy of the second fold

df_test2 = pd.read_csv("test2.txt", sep=",", names=[str(i) for i in range(18)])
df_train2 = pd.read_csv("train2.txt", sep=",", names=[str(i) for i in range(18)])


X = df_train2.ix[:,2:].as_matrix()
y = df_train2.ix[:,1].as_matrix()

x0 = df_test2.ix[:,2:].as_matrix()
y_true = df_test2.ix[:,1].as_matrix()

clf = SVC(C=1.0,kernel='linear')
clf.fit(X, y) 

y_pred = clf.predict(x0)


from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
print confusion_matrix(y_true, y_pred)
print accuracy_score(y_true, y_pred)
acc2 = accuracy_score(y_true, y_pred)

[[64  4]
 [ 0 41]]
0.963302752294


In [133]:
# Get the accuracy of the third fold

df_test3 = pd.read_csv("test3.txt", sep=",", names=[str(i) for i in range(18)])
df_train3 = pd.read_csv("train3.txt", sep=",", names=[str(i) for i in range(18)])

X = df_train3.ix[:,2:].as_matrix()
y = df_train3.ix[:,1].as_matrix()

x0 = df_test3.ix[:,2:].as_matrix()
y_true = df_test3.ix[:,1].as_matrix()

clf = SVC(C=1.0,kernel='linear')
clf.fit(X, y) 

y_pred = clf.predict(x0)

from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
print confusion_matrix(y_true, y_pred)
print accuracy_score(y_true, y_pred)
acc3 = accuracy_score(y_true, y_pred)

[[64  1]
 [ 4 40]]
0.954128440367


In [107]:
accs = [acc1, acc2, acc3]
print np.mean(accs)
print np.std(accs)

0.957186544343
0.00432481211735


In [134]:
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.model_selection import GridSearchCV


C_range = np.logspace(-2, 10, 13)
gamma_range = np.logspace(-9, 3, 13)
param_grid = dict(gamma=gamma_range, C=C_range)
cv = StratifiedShuffleSplit(n_splits=5, test_size=0.2, random_state=42)
grid = GridSearchCV(SVC(), param_grid=param_grid, cv=cv)
grid.fit(X, y)

print("The best parameters are %s with a score of %0.2f"
      % (grid.best_params_, grid.best_score_))


The best parameters are {'C': 10.0, 'gamma': 0.01} with a score of 0.98


In [121]:
df_validate = pd.read_csv("validate.txt", sep=",", names=[str(i) for i in range(18)])
X_2d = df_validate.ix[:,3:].as_matrix()
y_2d = df_validate.ix[:,2].as_matrix()